name: crud-app
services:
  api:
    image: node:latest
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - BCRYPT_SALT_ROUNDS=12
      - JWT_SECRET=correct-horse-battery-staple
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=admin-password
      - PGDATABASE=records
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./api
        target: /api
    working_dir: /api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=records
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin-password
    volumes:
      - crudDB:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
volumes:
  crudDB: